version: '1'
services:

  speedtest:
    build: .
    restart: no
    volumes:
      - ./:/app

  restarter:
    image: docker:cli
    volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
    command: ["sh", "-c", "while true; do sleep 600; docker restart speedtest; done"]
    restart: unless-stopped
